eureka: 
 client: 
  serviceUrl: 
   defaultZone: http://localhost:8761/eureka/ #注册服务器地址
server:
  port: 8766
spring:
  application:
    name: cloud-zuul
zuul: 
 routes: 
  api-a: 
   path: /api-a/** #所有的/api-a开头的请求都转发到cloud-consumer-ribbon服务器上
   serviceId: cloud-consumer-ribbon
  api-b: 
   path: /api-b/** #所有的/api-b开头的请求都转发到cloud-consumer-feign服务器上
   serviceId: cloud-consumer-feign